name: Latest Blog Posts
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog-posts:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in curtiscode.dev posts
        uses: curtiscde/blog-post-workflow@f
        with:
          feed_list: "https://curtiscode.dev/index.xml"