name: Latest Blog Posts
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  update-readme-with-blog-posts:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in curtiscode.dev posts
        uses: curtiscde/blog-post-workflow@master
        with:
          feed_list: "https://deploy-preview-95--curtistimson.netlify.app/index.xml"